# This is a sample build configuration for Python.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
image: continuumio/miniconda3

pipelines:
  default:
    - step:
        script:
          - conda --version
          - python --version
          - conda config --add channels glotzer
          - conda config --add channels conda-forge
          - conda create -n py35 --yes python=3.5 signac signac-flow signac-utils
          - source activate py35
          - cd projects
          - ./run-tests.sh
