# CircleCI configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  
  linux-python-38: &linux-template
    docker:
      - image: circleci/python:3.8

    environment:
      PYTHON: python

    working_directory: ~/repo

    steps:

      - checkout
      - run:
          name: install dependencies
          command: |
            export PATH=$PATH:$HOME/.local/bin
            ${PYTHON} -m pip install --progress-bar off -U virtualenv --user
            mkdir -p ./venv
            virtualenv ./venv --clear
            . venv/bin/activate
            conda --version
            python --version
            conda config --add channels conda-forge
            conda create -n py38 --yes python=3.8 signac signac-flow 
            source activate py38
            apt-get update
            apt-get --yes install quantum-espresso
            which pw.x

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd projects
            ./run-tests.sh --output           

workflows:
  version: 2
  test:
    jobs:
      - linux-python-38

