# CircleCI configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  
  linux-python-38: &linux-template
    docker:
      - image: circleci/python:3.8

    environment:
      PYTHON: python

    working_directory: ~/repo

    steps:

      - checkout
      - run:
          name: install dependencies
          command: |
            wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p "$HOME"/miniconda
            source miniconda/etc/profile.d/conda.sh
            conda activate base
            conda config --set always_yes yes --set auto_update_conda false
            conda update conda
            conda create -n test python=$PYTHON_VERSION
            conda activate test
            conda install -n test --file requirements.txt
            conda install -n test anaconda-project flake8 pillow mock pytest pytest-cov
            export PATH=$PATH:$HOME/.local/bin
            pip install conda
            conda --version
            python --version
            conda config --add channels conda-forge
            conda create -n py38 --yes python=3.8 signac signac-flow 
            source activate py38
            apt-get update
            apt-get --yes install quantum-espresso
            which pw.x

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd projects
            ./run-tests.sh --output           

workflows:
  version: 2
  test:
    jobs:
      - linux-python-38

